### ISSUE TITLE
Error downloading Pyhon 

### ISSUE THREAD

**Issue by PrestigeDevop** [microsoft/Windows-Machine-Learning#454]
## I'm submitting a…
 Bug report (I searched for similar issues and did not find one) 

The Run command doesn't work , and Save model as well , when trying to download Python in Convert tab  this error occurs 
```
reparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
    from termcolor import VERSION
  ModuleNotFoundError: No module named 'termcolor'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/termcolor-1.1.0.tar.gz# (from https://pypi.org/simple/termcolor/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement termcolor>=1.1.0 (from tensorflow) (from versions: 0.1, 0.1.1, 0.1.2, 0.2, 1.0.0, 1.0.1, 1.1.0)
ERROR: No matching distribution found for termcolor>=1.1.0
INFO: pip is looking at multiple versions of h5py,coremltools,winmltools - to determine which version is compatible with other requirements. This could take a while.
Error: Child process C:\Users\hi\AppData\Local\WinMLDashboard\python\python.exe exited with code 1
    at ChildProcess.<anonymous> (file:///C:/Users/hi/AppData/Local/WinMLDashboard/app-0.7.0/resources/app/build/static/js/main.5085b59a.js:1:264362)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12): Child process C:\Users\hi\AppData\Local\WinMLDashboard\python\python.exe exited with code 1
```

## Minimal reproduction of the problem with instructions
I've Python 3.7 Python 3.9 already installed 

 I
when using a model then in convert tap , download a new python binary for WInML Dashboard .
 

## Environment

Windows Build Number:

App min and target version:

OS Version (Server, IoT Core, Desktop, etc):

Graphics Driver version:

DxDiag:z

WinMLTools specific:
	- Source training framework: (e.g. CoreML, Scikit-learn, …)(TF converted to k5 and other binary model  using Google teachable machine 
        - WinMLTools version: 0.7.0

Visual Studio 
- [ ] 2019 LTS
- [ ] 2021 Preview

**Comment by PrestigeDevop** [comment]
Error  when loading Keras model foreach loop isn't a function

**Comment by nums11** [comment]
Thanks for posting, we're looking into this issue.
